### ISSUE TITLE
Unknown command 'echo_color'

### ISSUE THREAD

**Issue by dalln1** [fishery/simple#4]
After installing simple with fisherman I get this error in the terminal (termite on archlinux):

```
fish: Unknown command 'echo_color'
~/.config/fisherman/functions/fish_right_prompt.fish (line 17):
echo_color 555 (date "+%H:%M")
^
in function “fish_right_prompt”
	called on standard input

in command substitution
	called on standard input
```
Thanks for the great work!

**Comment by laughedelic** [comment]
I have the same problem. I tried to install echo_color from directly from the repository (because it's not in the fisherman index) and then I was getting errors on each fish launch..

**Comment by dalln1** [comment]
With [Fin](https://github.com/fishery/fin) it seems to work without errors. :+1:

**Comment by bucaran** [comment]
Hey folks, this is all my fault and failure to notify to @sotayamashita that `echo_color` is going to be deprecated.

It works with fin, because fin looks for plugins inside `fishery` by default if the namespace is not given.

I will update `simple` to not use `echo_color` as I would like to deprecate that plugin.

EDIT: The reason I want to deprecate that plugin is because it's too limited and IMO not worth having.

**Comment by bucaran** [comment]
Fixed, `simple` should work now and `echo_color` was finally removed.

**Comment by sotayamashita** [comment]
@bucaran Thanks you fixing my issue.
